spring:
  application:
    name: "eureka-server"
  config:
    import: "optional:configserver:http://localhost:8888/"

management:
  endpoints:
    web:
      exposure:
        exclude: "*"

  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

