server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URL}
          default-label: main
          search-paths:
            - user-service
            - book-service
          clone-on-start: true
      fail-fast: true
